name: flutter_runtime_env
description: Gives you some information about the runtime env.
  Such as if it is running in the Firebase TestLab
version: 0.0.4
homepage: https://gitjournal.io

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.gitjournal.flutter_runtime_env
    pluginClass: FlutterRuntimeEnvPlugin
